### PR TITLE
Backend logic for raid function

### PR DESCRIPTION
**Pull request by Kalinow**
Requirements for pull requests

Please refer to our Contribution Guide. What we would like to know from you:

* what did you change?
* why did you change it? why should it be in master?
** fixes
** features
** other benefits
* which issues are solved by this?

### CODE REVIEW

**Comment by Christoph-Meyer** [comment]
Hi @Kalinow ,
please fix the failing 2 tests first before issueing a PR.
When all checks pass I can merge your changes into master.
Regards

**Comment by Christoph-Meyer** [comment]
Hi @Kalinow, I have seen the PR and tried to make sense of the error msg from travis but I am not sure how to solve the issue. Any idea?

**Comment by sdibernardo** [comment]
See here: [Link](https://issues.sonatype.org/browse/MVNCENTRAL-4985?focusedCommentId=774922&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-774922)
Seems like a common problem with rate limits from Travis accessing Maven Central. Quick solution might be to provide an alternative mirror and trigger another build of this PR.

**Comment by sdibernardo** [comment]
Retriggered the build and it still fails but with another error.

**Comment by Kalinow** [comment]
Hello :)
Sorry! I thought I was working on my copied fork.
I will fix the problems and start a new request.

**Comment by Christoph-Meyer** [comment]
Hi @Kalinow there is still one NPE in your test left, that's why Travis failed. ;-)

**Comment by surfermicha** [comment]
@Kalinow , you added a very interesting feature to SonarQuest. Can we assist you making it ready to be merged?

**Review by Christoph-Meyer — APPROVED** [review]

**Pull request closed without merging**
