### PR TITLE
Fixed issue #253 where basic authentication credentials are not updated.

### PR DESCRIPTION
**Pull request by shawly**
Fixed issue https://github.com/viadee/sonarQuest/issues/253 where basic auth is not updated properly.

### CODE REVIEW

**Comment by shawly** [comment]
Seems like you build process isn't working..

**Comment by fkoehne** [comment]
Thanks for your interest and contribution. Your build failed because the branch is not part of our repository configuration yet (and hence that particular build process does not know our credentials for sonarsource - and I don't have an acceptable solution for this right now). 

You did not break any tests though. @surfermicha will make a decision on how to proceed.

**Comment by shawly** [comment]
> You did not break any tests though. @surfermicha will make a decision on how to proceed.

If you're open to suggestions, you might want to add some mocking frameworks like Mockito, JMockit or EasyMock to make testing logic easier. 
Also I'd suggest enforcing the AAA pattern on future tests. I've seen a few tests which could profit from it. I've also seen a lot of tests which violate the Single Responsibility Principle because they test more than one scenario which makes maintainability harder in the long run.
Using mocking frameworks could also help to reduce SRP violations you got in a few tests I've seen.

Anyway it's a really cool project and I'm really happy to contribute! I hope to see a some more activity soon, I've shown SonarQuest to a few of my colleagues and they are considering on helping the development. It's still a little rough around the edges, but as soon as they are filed down, we might use it to help our fight against legacy code! :)

**Comment by surfermicha** [comment]
Hey @shawly!

thanks for your effort on helping SonarQuest to grow and sorry for waiting so long fo an answer.
We invited you to our community group so that you can also use the sonarcloud check and have successful travis builds. When you open you next pull request we can see if it works. Thanks for your patience! i'm looking forward for your next commits :)

**Pull request closed without merging**
